let seuvotopara=document.querySelector('.d-1-1 span')
let cargo=document.querySelector('.d-1-2 span')
let descricao=document.querySelector('.d-1-4')
let aviso=document.querySelector('.divisao2')
let lateral=document.querySelector('.d-1right')
let numeros=document.querySelector('.d-1-3')